rss/urls.py
from django.conf.urls import patterns, url
from rss import views

urlpatterns = patterns('',
	url(r'^$', views.RssView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.RssUpdateView.as_view(), name='update'),
	url(r'^temp', views.WordView.as_view(), name='word'),
	url(r'^delete', views.EntryDelete.as_view(), name='deleted'),
)

styria/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('rss.urls', namespace="rss")),
)

rss/models.py
from django.db import models

class Feed(models.Model):
	link = models.URLField()
	status = models.BooleanField("RSS feed aktivan?", default = True)

	def __unicode__(self):
		return self.link

class Entry(models.Model):
	title = models.CharField(max_length=300)
	url = models.URLField()
	description = models.TextField()
	feed = models.ForeignKey(Feed)

	def __unicode__(self):
		return self.title

class Word(models.Model):
	word = models.CharField(max_length=50)
	
	def __unicode__(self):
		return self.word

class WordCount(models.Model):
	word = models.ForeignKey(Word)
	entry = models.ForeignKey(Entry)
	sum_entry = models.IntegerField(default=0)
	feed = models.ForeignKey(Feed)
	sum_feed = models.IntegerField(default=0)
	total = models.IntegerField(default=0)

	def __unicode__(self):
		return self.word

rss/forms.py
from django.forms import ModelForm
from django import forms
from rss.models import *

class RssForm(ModelForm):
	class Meta:
		model = Feed

rss/views.py
from django.views.generic import ListView, View
from django.views.generic.edit import FormMixin, UpdateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render_to_response, render
import feedparser

from rss.models import *
from rss.forms import *


class RssFormMixin(FormMixin):
	'''
		Feed forma
	'''
	form_class = RssForm
	success_url = '/'

	def form_valid(self, form):
		form.save()
		return super(RssFormMixin, self).form_valid(form)

	def form_invalid(self, form):
		return super(RssFormMixin, self).form_valid(form)

	def post(self, form):
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

class RssView(RssFormMixin, ListView):
	'''
		Feed forma & Feed lista
	'''
	template_name = "rss/index.html"
	model = Feed
	paginate_by = 10

	def get_queryset(self):
		return Feed.objects.order_by('-pk')

	def get(self, *args, **kwargs):
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		self.object_list = self.get_queryset()
		allow_empty = self.get_allow_empty()
		if not allow_empty and len(self.object_list) == 0:
			raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.") % {'class_name': self.__class__.__name__})
		context = self.get_context_data(object_list=self.object_list, form=form, **kwargs)
		return self.render_to_response(context)

class RssUpdateView(UpdateView):
	'''
		Feed (status) editiranje
	'''
	template_name = "rss/update.html"
	model = Feed

	def get_success_url(self):
		return reverse('rss:index')

	def get_context_data(self, **kwargs):
		context = super(RssUpdateView, self).get_context_data(**kwargs)
		context['action'] = reverse('rss:update', kwargs={'pk': self.get_object().pk})
		return context

class Words():

	def word_count():
		feed = feedparser.parse('https://sg.entertainment.yahoo.com/rss/')
		for i in range(0, len(feed['entries'])):
			p = Entry.objects.create(
				title = feed['entries'][i].title,
				description = feed['entries'][i].description,
				url = feed['entries'][i].link,
				feed = Feed.objects.get(id=1)
			)
			p.save
	
		# context = {'title': title, 'description': description, 'url': url,}
		# return render(request, 'rss/temp.html', context)
	
# 	def remove_tags(description):
# 		result = 0
# 		return result

class EntryDelete(ListView):

	def entry_delete():
		if Entry.objects.count() > 200:
			for i in range(0, 200):
				Entry.objects.all()[i].delete()
			
	entry_delete()

	template_name = "rss/delete.html"
	model = Entry
	paginate_by = 10

	def get_queryset(self):
		return Entry.objects.all()
	
class WordView(ListView):
	
	def word_count():
		feed = feedparser.parse('https://sg.entertainment.yahoo.com/rss/')
		for i in range(0, len(feed['entries'])):
			p = Entry.objects.create(
				title = feed['entries'][i].title,
				description = feed['entries'][i].description,
				url = feed['entries'][i].link,
				feed = Feed.objects.get(id=1)
			)
			# p.save()


	word_count()

	template_name = "rss/temp.html"
	model = Entry
	paginate_by = 10

	def get_queryset(self):
		return Entry.objects.all()

# class Iz(object):
# 	def novi(self):
# 		data = 3
# 		return data

# class Print(Iz, View):
# 	def izlaz(request):
# 		context = 3
# 		# Super(Iz, self).novi()
# 		return render(request, 'rss/temp.html', {'data': context})
# 	izlaz(self)

rss/templates/rss/delete.html
{% if entry_list %}
	<ul>
	{% for entry in entry_list %}
		<li>{{ entry.title }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>Lista je prazna!</p>
{% endif %}


{% if is_paginated %}
<div class="pagination">
	<span class="links">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">previous</a>
		{% endif %}
		<span class="current">
			Page {{ page_obj.number }} of {{ paginator.num_pages }}
		</span>
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">next</a>
		{% endif %}
	</span>
</div>
{% endif %}

rss/templates/rss/index.html
<h2>Forma</h2>

<form action="{% url 'rss:index' %}" method="POST">{% csrf_token %}
	<ul>
		{{ form.as_ul }}
	</ul>
	<input type="submit" value="Unos" />
</form>
<form action="{% url 'rss:word' %}">
	<input type="submit" value="Spremi sve feedove" />
</form>
<form action="{% url 'rss:deleted' %}">
	<input type="submit" value="Obrisi sve feedove" />
</form>
	
<h2>Lista</h2>

{% if feed_list %}
	<ul>
	{% for feed in feed_list %}
		<li>{{ feed.link }} - {% if feed.status == 1 %}aktivan{% elif feed.status == 0 %}nije aktivan{% else %}error{% endif %} --- <a href="{% url 'rss:update' feed.pk %}">EDIT</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>Lista je prazna!</p>
{% endif %}

{% if is_paginated %}
<div class="pagination">
	<span class="links">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">previous</a>
		{% endif %}
		<span class="current">
			Page {{ page_obj.number }} of {{ paginator.num_pages }}
		</span>
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">next</a>
		{% endif %}
	</span>
</div>
{% endif %}

rss/templates/rss/temp.html
{% comment %}
	
{% if entry_list %}
	<ul>
	{% for entry in entry_list %}
		<li>{{ entry.title }} </li>
	{% endfor %}
	</ul>
{% else %}
	<p>Lista je prazna!</p>
{% endif %}
{% endcomment %}
{{ data }}
{% if is_paginated %}
<div class="pagination">
	<span class="links">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">previous</a>
		{% endif %}
		<span class="current">
			Page {{ page_obj.number }} of {{ paginator.num_pages }}
		</span>
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">next</a>
		{% endif %}
	</span>
</div>
{% endif %}

rss/templates/rss/update.html
<h2>Update</h2>

<form action="{{ action }}" method="POST">{% csrf_token %}
	<ul>
		{{ form.as_ul }}
	</ul>
	<input type="submit" value="Edit" />
</form>
<form action="{% url 'rss:index' %}">
	<input type="submit" value="Home">
</form>